let customers = [
  {
    name: "Golam Aziz Tanvir",
    price: 1220,
    payment: "paid",
    status: "delivered",
    img: "./img/user.jpg",
    country: "Bangladesh",
  },
  {
    name: "Mizanur rahman",
    price: 220,
    payment: "paid",
    status: "inprogress",
    img: "./img/user.jpg",
    country: "Bangladesh",
  },
  {
    name: "Sakib Al Hasan",
    price: 1500,
    payment: "due",
    status: "return",
    img: "./img/user.jpg",
    country: "Bangladesh",
  },
  {
    name: "Golam Sarwar Tarek",
    price: 500,
    payment: "paid",
    status: "pending",
    img: "./img/user.jpg",
    country: "Bangladesh",
  },
  {
    name: "Golam Afsar Tanjid",
    price: 1220,
    payment: "paid",
    status: "delivered",
    img: "./img/user.jpg",
    country: "Bangladesh",
  },
  {
    name: "Golam Mawla Babul",
    price: 1220,
    payment: "paid",
    status: "inprogress",
    img: "./img/user.jpg",
    country: "Bangladesh",
  },
  {
    name: "Asif Hasan",
    price: 1220,
    payment: "due",
    status: "return",
    img: "./img/user.jpg",
    country: "Bangladesh",
  },
  {
    name: "Tanvir Mahmud",
    price: 1220,
    payment: "paid",
    status: "pending",
    img: "./img/user.jpg",
    country: "Bangladesh",
  },
  {
    name: "Ali Hosen Jibon",
    price: 1220,
    payment: "due",
    status: "delivered",
    img: "./img/user.jpg",
    country: "Bangladesh",
  },
  {
    name: "tamim iqbal",
    price: 1220,
    payment: "paid",
    status: "inprogress",
    img: "./img/user.jpg",
    country: "Bangladesh",
  },
  {
    name: "Saiful Islam",
    price: 900,
    payment: "due",
    status: "return",
    img: "./img/user.jpg",
    country: "Bangladesh",
  },
  {
    name: "Momotaj Begum",
    price: 700,
    payment: "paid",
    status: "pending",
    img: "./img/user.jpg",
    country: "Bangladesh",
  },
  {
    name: "Shamima Begum",
    price: 1500,
    payment: "paid",
    status: "return",
    img: "./img/user.jpg",
    country: "Bangladesh",
  },
  {
    name: "Fariha Aktar",
    price: 1300,
    payment: "due",
    status: "pending",
    img: "./img/user.jpg",
    country: "Bangladesh",
  },
  {
    name: "Momotaz Begum",
    price: 2000,
    payment: "paid",
    status: "return",
    img: "./img/user.jpg",
    country: "Bangladesh",
  },
  {
    name: "Bibi Fatema",
    price: 1000,
    payment: "due",
    status: "delivered",
    img: "./img/user.jpg",
    country: "Bangladesh",
  },
];
